# Generated by Django 3.1.1 on 2020-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('updated', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'Articles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tagmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('tag_id', models.IntegerField()),
                ('in_title', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
            options={
                'db_table': 'TagMaps',
                'managed': False,
            },
        ),
    ]
